using System;
using System.Collections.Generic;

namespace BozjaBuddyReborn.Automation;

public readonly record struct DiagnosticEntry(
    DateTimeOffset Timestamp,
    ControllerState State,
    string Message);

/// <summary>
/// Small privacy-safe in-memory history for unattended-run diagnostics.
///
/// It deliberately records only controller state/status text generated by BBR itself. Character
/// names, world, chat, party member names and arbitrary user text never enter this recorder.
/// </summary>
public static class DiagnosticsRecorder
{
    private const int MaxTransitions = 32;
    private const int MaxWarnings = 16;

    private static readonly object Gate = new();
    private static readonly Queue<DiagnosticEntry> Transitions = new();
    private static readonly Queue<DiagnosticEntry> Warnings = new();

    private static bool _hasObservation;
    private static ControllerState _lastState;
    private static string _lastStatus = string.Empty;
    private static string _lastWarning = string.Empty;

    public static IReadOnlyList<DiagnosticEntry> StateTransitions
    {
        get { lock (Gate) return Transitions.ToArray(); }
    }

    public static IReadOnlyList<DiagnosticEntry> WarningHistory
    {
        get { lock (Gate) return Warnings.ToArray(); }
    }

    public static string LatestWarning
    {
        get { lock (Gate) return _lastWarning; }
    }

    public static void Observe(ControllerState state, string? status)
    {
        status ??= string.Empty;
        lock (Gate)
        {
            if (!_hasObservation || state != _lastState || !string.Equals(status, _lastStatus, StringComparison.Ordinal))
            {
                Enqueue(Transitions, new DiagnosticEntry(DateTimeOffset.Now, state, status), MaxTransitions);
                _hasObservation = true;
                _lastState = state;
                _lastStatus = status;
            }

            if (LooksLikeWarning(state, status) && !string.Equals(status, _lastWarning, StringComparison.Ordinal))
            {
                _lastWarning = status;
                Enqueue(Warnings, new DiagnosticEntry(DateTimeOffset.Now, state, status), MaxWarnings);
            }
        }
    }

    public static void Warning(string message, ControllerState state = ControllerState.Blocked)
    {
        if (string.IsNullOrWhiteSpace(message))
            return;

        lock (Gate)
        {
            if (string.Equals(message, _lastWarning, StringComparison.Ordinal))
                return;
            _lastWarning = message;
            Enqueue(Warnings, new DiagnosticEntry(DateTimeOffset.Now, state, message), MaxWarnings);
        }
    }

    public static void Clear()
    {
        lock (Gate)
        {
            Transitions.Clear();
            Warnings.Clear();
            _hasObservation = false;
            _lastState = ControllerState.Idle;
            _lastStatus = string.Empty;
            _lastWarning = string.Empty;
        }
    }

    private static bool LooksLikeWarning(ControllerState state, string status)
    {
        if (state == ControllerState.Blocked)
            return true;
        if (string.IsNullOrWhiteSpace(status))
            return false;

        return status.Contains("失敗", StringComparison.Ordinal)
               || status.Contains("タイムアウト", StringComparison.Ordinal)
               || status.Contains("利用できません", StringComparison.Ordinal)
               || status.Contains("未接続", StringComparison.Ordinal)
               || status.Contains("接続が失われ", StringComparison.Ordinal)
               || status.Contains("停止", StringComparison.Ordinal);
    }

    private static void Enqueue(Queue<DiagnosticEntry> queue, DiagnosticEntry entry, int max)
    {
        queue.Enqueue(entry);
        while (queue.Count > max)
            queue.Dequeue();
    }
}
