from __future__ import annotations
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def replace_many(path: str, pairs: list[tuple[str, str]]) -> None:
    p = ROOT / path
    text = p.read_text(encoding="utf-8-sig")
    changed = 0
    for old, new in pairs:
        if old in text:
            text = text.replace(old, new)
            changed += 1
    if changed:
        p.write_text(text, encoding="utf-8")
    print(f"{path}: localized {changed} visible string group(s)")


replace_many("Windows/MainWindow.cs", [
    ('"Stop party support"', '"パーティ支援を停止"'),
    ('"Start party support"', '"パーティ支援を開始"'),
    ('"Party support is idle."', '"パーティ支援は待機中です。"'),
    ('$"({task.Applied} cast)"', '$"（{task.Applied}回使用）"'),
    ('"Only take engagements and skirmishes in this third of the zone.\\n"', '"このエリア内のCEとスカーミッシュだけを対象にします。\\n"'),
    ('"Zone names shown are for the zone you are in; the number (Z1/Z2/Z3) is what is stored,\\n"', '"表示名は現在のフィールドに合わせますが、保存されるのはZ1/Z2/Z3の区分です。\\n"'),
    ('"so the same choice carries across both Bozja and Zadnor."', '"同じ区分設定が南方ボズヤ戦線とザトゥノル高原の両方に適用されます。"'),
    ('$"Farming here: {farm.Describe()}"', '$"現在のFarm対象: {farm.Describe()}"'),
    ('$"Farm target is {farm.Describe()} - you are not there."', '$"Farm対象は {farm.Describe()} です。現在地が対象外です。"'),
    ('$"{mettle:N0} / {needed:N0} mettle"', '$"戦果 {mettle:N0} / {needed:N0}"'),
    ('$"{mettle:N0} mettle"', '$"戦果 {mettle:N0}"'),
    ('label += "  [duel]";', 'label += "  [一騎打ち]";'),
    ('label += "  [large-scale]";', 'label += "  [大規模戦闘]";'),
    ('ImGui.SetTooltip("Never travel to this engagement.");', 'ImGui.SetTooltip("この対象には参加・移動しません。");'),
    ('"Uses a local named pipe, the same approach AutoDuty takes. One client is the host and\\n"', '"AutoDutyと同様に、このPC内のローカルNamed Pipeで連携します。1クライアントをホストにし、\\n"'),
    ('"picks the objective; the others follow it, so the boxes never split up."', '"ホストが目的地を決め、他クライアントが追従することで分散を防ぎます。"'),
    ('ImGui.SetTooltip("Exactly one client in the group should be the host.");', 'ImGui.SetTooltip("グループ内でホストにするクライアントは1つだけにしてください。");'),
    ('"Wait for every box to arrive before committing"', '"全クライアント到着後に戦闘開始する"'),
    ('"Barrier timeout (s)"', '"到着待ちタイムアウト（秒）"'),
    ('ImGui.SetTooltip("The host releases the group anyway after this long, so one stuck box cannot stall everyone.");', 'ImGui.SetTooltip("この時間を超えると、1クライアントが詰まっていてもホストが待機を解除します。");'),
    ('ImGui.TextColored(Green, "Link up");', 'ImGui.TextColored(Green, "接続済み");'),
    ('$"Connecting to the host... (attempt {_link.ConsecutiveFailures + 1})"', '$"ホストへ接続中…（試行 {_link.ConsecutiveFailures + 1}）"'),
    ('ImGui.TextColored(Red, "No host is listening on this PC.");', 'ImGui.TextColored(Red, "このPC上でホストが見つかりません。");'),
    ('$"Searching for {_link.SecondsSearching:F0}s ({_link.ConsecutiveFailures} attempts"', '$"検索中 {_link.SecondsSearching:F0}秒（{_link.ConsecutiveFailures}回試行"'),
    ('(_link.LastLinkError is { } err ? $", last: {err}" : "")', '(_link.LastLinkError is not null ? ", 直近エラーあり（診断ログ参照）" : "")'),
    ('"Tick \\"This client is the host\\" on exactly ONE of your boxes - every box\\n"', '"どれか1つのクライアントだけで「このクライアントをホストにする」をONにしてください。\\n"'),
    ('"defaults to client, so a fresh setup has no host at all. Running alone\\n"', '"初期状態は全クライアントが子機なので、そのままではホストが存在しません。単独動作中も\\n"'),
    ('"meanwhile: the deterministic pick still converges on the same objective."', '"決定論的な対象選択により、各クライアントは同じ目的地へ収束します。"'),
    ('_link.IsHost ? "Hosting - waiting for boxes to join" : "Link idle"', '_link.IsHost ? "ホスト中 - 他クライアントの接続待ち" : "リンク待機中"'),
    ('$"Role: {(_link.IsHost ? "host" : "client")}   Peers: {_link.PeerCount}"', '$"役割: {(_link.IsHost ? "ホスト" : "クライアント")}   接続数: {_link.PeerCount}"'),
    ('"No other box has connected yet. The others must have multibox enabled and must\\n"', '"まだ他クライアントは接続していません。他クライアント側でもマルチボックスを有効にし、\\n"'),
    ('"NOT be ticked as host."', '"ホスト設定はOFFにしてください。"'),
    ('$"Arrived: {_link.ArrivedCount}/{_link.PeerCount}"', '$"到着: {_link.ArrivedCount}/{_link.PeerCount}"'),
    ('? $"Shared objective: {objective.Kind} #{objective.Id}"', '? $"共有目的地: #{objective.Id}"'),
    (': "Shared objective: none"', ': "共有目的地: なし"'),
    ('"Drive every box from one place - start/stop, push Lost Action loadouts, and send"', '"1画面から全クライアントの開始/停止、ロストアクション構成の送信、"'),
    ('" boxes to the nearest aetheryte or cache. Also on /bbr boxes."', '"最寄りエーテライトやロストボックスへの移動を操作できます。/bbr boxes でも開けます。"'),
    ('"Every connected box\'s two Duty Action slots on one bar - icon, charges and recharge,\\n"', '"接続中の全クライアントのDuty Action 2枠を、アイコン・残数・リキャスト付きで1画面に表示します。\\n"'),
    ('"the same information you see for your own. Also on /bbr duty."', '"自分の枠と同じ情報を確認できます。/bbr duty でも開けます。"'),
    ('"Even with the link down, every box runs the same deterministic pick, so they still\\n"', '"リンクが切れても各クライアントは同じ決定論的選択を行うため、\\n"'),
    ('"converge on the same engagement instead of scattering."', '"別々の対象へ散らばりにくい設計です。"'),
    ('Row("vnavmesh", _navmesh.Available, "movement and pathfinding - required");', 'Row("vnavmesh", _navmesh.Available, "移動・経路探索（必須）");'),
    ('BossModFork.Reborn => "AoE avoidance only - AI in ForbidActions, no AI preset, autorotation force-disabled"', 'BossModFork.Reborn => "AoE回避専用。AIはForbidActions、AIプリセットなし、自動ローテーション無効"'),
    ('BossModFork.Original => "AoE avoidance only - AI mode with auto-target off, no rotation preset active"', 'BossModFork.Original => "AoE回避専用。自動ターゲットOFF、ローテーションプリセットなし"'),
    ('_ => "AoE avoidance - either fork works; Reborn is preferred"', '_ => "AoE回避。どちらのforkでも動作しますがRebornを推奨"'),
    ('ImGui.TextColored(Red, reason);', 'ImGui.TextColored(Red, "BossModとの接続に失敗しています。詳細は /xllog を確認してください。");'),
    ('"BossMod Reborn (FFXIV-CombatReborn/BossmodReborn) gives the fullest integration - it reports\\n"', '"BossMod Rebornは回避中かどうかを取得できるため、最も完全な連携ができます。\\n"'),
    ('"when it is dodging, so travel yields to it. The original awgil BossMod also works, with\\n"', '"回避中は移動制御をBossModへ譲ります。オリジナル版BossModでも動作しますが、\\n"'),
    ('"the differences listed below."', '"下記の制約があります。"'),
    ('"Both BossMod forks are loaded. They register the same BossMod.* IPC gates, so whichever\\n"', '"BossModの2つのforkが同時に読み込まれています。同じBossMod.* IPCを共有するため、\\n"'),
    ('"loaded last owns them and unloading either strips them - unload one. Driving Reborn."', '"後から読み込まれた側が競合します。どちらか一方をアンロードしてください。現在はRebornを使用します。"'),
    ('Row("Rotation Solver Reborn", _director.RotationAvailable, "the rotation");', 'Row("Rotation Solver Reborn", _director.RotationAvailable, "戦闘ローテーション（必須）");'),
    ('ImGui.TextColored(Grey, "Roles");', 'ImGui.TextColored(Grey, "役割分担");'),
    ('ImGui.BulletText($"{avoidance.ForkName} moves you out of telegraphed AoEs. It presses no buttons.");', 'ImGui.BulletText($"{avoidance.ForkName}: 予兆AoEから移動して回避します。戦闘アクションは押しません。");'),
    ('ImGui.BulletText("RSR runs the rotation. It is the only thing queueing actions.");', 'ImGui.BulletText("RSR: 戦闘ローテーションを実行し、戦闘アクションの入力を担当します。");'),
    ('ImGui.BulletText("The original closes on the target itself (FollowSlot); our own approach stands down.");', 'ImGui.BulletText("オリジナル版はFollowSlotで対象へ接近するため、BBR側の接近制御を停止します。");'),
    ('ImGui.BulletText("It cannot say when it is dodging, so travel cannot yield to a dodge mid-path -");', 'ImGui.BulletText("オリジナル版は回避中か判定できないため、経路移動中に回避へ制御を譲れません。");'),
    ('"it only dodges while we are not pathing (holds, and once arrived). Reborn dodges en route too."', '"経路移動していない待機中・到着後のみ回避します。Rebornは移動中も回避できます。"'),
    ('ImGui.TextColored(Grey, "Avoidance telemetry");', 'ImGui.TextColored(Grey, "回避テレメトリ");'),
    ('$"Danger zones active: {zones}"', '$"危険領域: {zones}"'),
    ('$"BossMod wants to move: {(navigating ? "yes" : "no")}"', '$"BossMod移動要求: {(navigating ? "あり" : "なし")}"'),
    ('$"=> yielding movement: {(_director.AvoidanceIsSteering ? "yes" : "no")}"', '$"=> 移動制御を譲渡: {(_director.AvoidanceIsSteering ? "はい" : "いいえ")}"'),
    ('"BossMod wants to move but reports no telegraphed danger - that is\\n"', '"BossModは移動を要求していますが危険予兆はありません。これは\\n"'),
    ('"repositioning, not a dodge, so travel keeps the path. This is normal."', '"位置調整であり回避ではないため、BBRの経路移動を継続します。正常動作です。"'),
    ('ImGui.TextColored(Grey, "Danger zones / steering: not reported by this fork (no Hints.* or AI.* gates).");', 'ImGui.TextColored(Grey, "危険領域/移動制御: このforkでは取得できません（Hints.* / AI.* IPCなし）。");'),
    ('$"Last sent - AI: {Age(avoidance.SecondsSinceSent)}, "', '$"最終送信 - AI: {Age(avoidance.SecondsSinceSent)}, "'),
    ('$"rotation: {_director.Rotation.CurrentMode?.ToString() ?? "nothing"} "', '$"rotation: {_director.Rotation.CurrentMode?.ToString() ?? "未設定"} "'),
    ('ImGui.Button("Re-apply avoidance-only config")', 'ImGui.Button("回避専用設定を再適用")'),
    ('"Re-asserts (read-before-write): AIConfig.ForbidActions = true, AIConfig.ForbidMovement = false,\\n"', '"現在値を確認してから AIConfig.ForbidActions=true / ForbidMovement=false を再適用し、\\n"'),
    ('"and Presets.ClearActive if any user preset or force-disable is in the active list.\\n"', '"ユーザープリセットやforce-disableが有効ならPresets.ClearActiveを実行します。\\n"'),
    ('"Deliberately NOT SetForceDisabled - in the original that removes the AI preset (the dodging)."', '"オリジナル版ではSetForceDisabledが回避AI自体を外すため、意図的に使用しません。"'),
    ('"Re-sends: /bmrai forbidactions on, /bmrai forbidmovement off,\\n"', '"/bmrai forbidactions on、/bmrai forbidmovement off を再送し、\\n"'),
    ('"AI.SetPreset(\\"\\") and Presets.SetForceDisabled()."', '"AI.SetPreset(\\"\\") と Presets.SetForceDisabled() を再適用します。"'),
    ('ImGui.Button($"Restore {avoidance.ForkName}")', 'ImGui.Button($"{avoidance.ForkName} の設定を復元")'),
    ('ImGui.SetTooltip("Stop the AI and put back the settings and presets we changed.");', 'ImGui.SetTooltip("AIを停止し、BBRが変更した設定・プリセットを元に戻します。");'),
    ('ok ? "OK  " : "MISSING  "', 'ok ? "OK  " : "未接続  "'),
    ('seconds < 0f ? "(never)" : $"{seconds:F0}s ago"', 'seconds < 0f ? "（未送信）" : $"{seconds:F0}秒前"'),
])

replace_many("Windows/ConfigWindow.cs", [
    (': base("Bozja Buddy Reborn - Settings###BozjaBuddyRebornConfig")', ': base("Bozja Buddy Reborn - 設定###BozjaBuddyRebornConfig")'),
    ('"The two plugins run in separate roles so they cannot fight each other:\\n"', '"2つのプラグインは役割を分離して競合を防ぎます。\\n"'),
    ('"BossMod dodges, RSR presses buttons."', '"BossModが回避、RSRが戦闘アクションを担当します。"'),
    ('"Works with BossMod Reborn (preferred) or the original awgil BossMod - whichever is loaded.\\n"', '"BossMod Reborn（推奨）またはオリジナル版BossModの、読み込まれている方を使用します。\\n"'),
    ('"Reborn: its AI is turned on with ForbidActions, its AI preset cleared and the global\\n"', '"Reborn: ForbidActionsでAIを有効にし、AIプリセットを空にして、グローバルの\\n"'),
    ('"autorotation force-disabled, so it dodges and never queues an action.\\n"', '"自動ローテーションを強制無効化するため、回避だけ行い戦闘アクションは入力しません。\\n"'),
    ('"Original: AI mode is turned on with auto-target off and any active rotation preset cleared -\\n"', '"オリジナル版: 自動ターゲットOFFでAIを有効化し、アクティブなローテーションプリセットを解除します。\\n"'),
    ('"its AI preset is only auto-target + follow + movement, so it has nothing to press anyway.\\n"', '"AIプリセットはターゲット・追従・移動のみになるため、戦闘アクションは入力しません。\\n"'),
    ('"Without these guards BossMod and RSR stall each other\'s action queue.\\n"', '"この分離を行わないとBossModとRSRのアクションキューが競合します。\\n"'),
    ('"Everything changed is restored when you stop."', '"停止時にはBBRが変更した設定を復元します。"'),
    ('"The original cannot report when it is dodging and only moves while we are not pathing,\\n"', '"オリジナル版は回避中か取得できず、BBRが経路移動していない時だけ移動できるため、\\n"'),
    ('"so it dodges at holds and once arrived; Reborn dodges en route as well."', '"待機中と到着後に回避します。Rebornは経路移動中も回避できます。"'),
    ('ImGui.TextColored(Grey, "RSR runs in Auto mode - it picks and attacks targets itself.");', 'ImGui.TextColored(Grey, "RSRはAutoモードで動作し、対象選択と攻撃を自動で行います。");'),
    ('ImGui.TextColored(Yellow, "With RSR off nothing will attack. You will have to fight manually.");', 'ImGui.TextColored(Yellow, "RSRをOFFにすると自動攻撃されません。戦闘は手動操作が必要です。");'),
    ('"Re-apply the avoidance config before every fight"', '"戦闘ごとに回避専用設定を再適用する"'),
    ('ImGui.SetTooltip("Slower, but survives you changing BossMod\'s settings mid-session.");', 'ImGui.SetTooltip("若干処理は増えますが、途中でBossMod設定を変更しても回避専用状態へ戻せます。");'),
    ('"Walk into range of the target while fighting"', '"戦闘中は対象の攻撃射程まで接近する"'),
    ('"BossMod Reborn only closes on a target when it is following a party master, and solo\\n"', '"BossMod Rebornはパーティマスター追従時以外は対象へ自動接近しません。ソロでは\\n"'),
    ('"the master is you - so in the avoidance-only setup this plugin uses, it dodges and\\n"', '"自分自身がマスターになるため、BBRの回避専用設定では回避だけを行い、\\n"'),
    ('"nothing else. Without this a melee job stands where travel left it and the rotation\\n"', '"接近は行いません。この設定がOFFだと近接ジョブが移動終了地点に立ち続け、\\n"'),
    ('"falls back to its ranged filler (Enpi on Samurai, and so on).\\n"', '"遠隔代替技（侍の燕飛など）だけを使う場合があります。\\n"'),
    ('"Melee and tanks are pulled to 2y inside the hitbox; everything else to 15y.\\n"', '"近接・タンクはヒットボックス内側2y、その他は15yまで接近します。\\n"'),
    ('"With the ORIGINAL BossMod this is bypassed: its FollowSlot module walks to the target\\n"', '"オリジナル版BossModではFollowSlotが自力で対象へ接近するため、この処理を使いません。\\n"'),
    ('"by itself, around the AoEs, and an approach path of ours would only make it yield."', '"AoEを避けながら接近するため、BBR側の接近経路を重ねる必要がありません。"'),
    ('"Re-assert combat state (s)"', '"戦闘状態の再適用間隔（秒）"'),
    ('"Re-sends the on/off state to both plugins on this interval even when it has not\\n"', '"状態が変化していなくても、この間隔で両プラグインへON/OFF状態を再送します。\\n"'),
    ('"changed. RSR and Reborn cannot be asked what state they are in, and both drop it on\\n"', '"RSRとRebornは現在状態を問い合わせられず、内部状態が解除される場合があるため、\\n"'),
    ('"their own - Reborn idles its AI whenever the party slot it follows goes invalid, which\\n"', '"定期的に再適用します。Rebornは追従中のパーティ枠が無効になるとAIを待機させます。\\n"'),
    ('"a Bozja alliance does constantly - so without this the run can continue with nothing\\n"', '"ボズヤのアライアンスではこれが頻繁に起きるため、再適用しないと\\n"'),
    ('"armed. The original BossMod\'s AI state IS readable, so its heartbeat only writes when\\n"', '"自動戦闘が解除されたまま周回を続ける可能性があります。オリジナル版はAI状態を読めるため、\\n"'),
    ('"something drifted (it force-disables itself on death, which would drop the dodging).\\n"', '"状態がずれた場合だけ書き戻します（死亡時など）。\\n"'),
    ('"0 turns it off."', '"0で再適用を無効化します。"'),
    ('"If RSR\'s \\"show toggled setting in chat\\" is on, each re-assert prints a line. Turn\\n"', '"RSR側の設定変更をチャット表示する機能がONだと、再適用ごとにメッセージが出ます。\\n"'),
    ('"that off in RSR, or raise this interval, if the chat noise bothers you."', '"気になる場合はRSR側の表示をOFFにするか、この間隔を長くしてください。"'),
    ('ImGui.TextUnformatted("When something aggroes onto you while travelling:");', 'ImGui.TextUnformatted("移動中に敵から感知された場合:");'),
    ('"Keep running holds the rotation OFF for the whole route, so nothing is attacked on the\\n"', '"「そのまま走る」では移動中のローテーションをOFFにし、道中の敵へ反撃しません。\\n"'),
    ('"way - field mobs leash and drop off once you outrun them. Stopping for every puller\\n"', '"十分に離れればフィールド敵は追跡をやめます。感知のたびに停止して戦うと、\\n"'),
    ('"instead turns one run into a string of fights that earn nothing and burn the\\n"', '"報酬のない戦闘が連続し、\\n"'),
    ('"registration window.\\n"', '"CEの参加受付時間を消費します。\\n"'),
    ('"Either way, attackers ARE answered once you have arrived: there is nowhere left to run,\\n"', '"目的地へ到着した後は、追ってきた敵にも反撃します。\\n"'),
    ('"and a Critical Engagement\'s registration window has to be waited out where you stand.\\n"', '"CEの抽選待機中など、その場を離れられない状況では戦闘を処理します。\\n"'),
    ('"Keyed on hostiles actually targeting you, not the in-combat flag, which lingers after\\n"', '"判定には戦闘フラグではなく、実際に自分をターゲットしている敵を使用します。\\n"'),
    ('"the last mob dies."', '"戦闘フラグは敵撃破後もしばらく残るためです。"'),
    ('"You cannot mount in combat, so while something is chasing you the run is on foot until\\n"', '"戦闘中はマウントできないため、敵に追跡されている間は徒歩で逃走し、\\n"'),
    ('"it leashes."', '"追跡が切れた後に再度マウントします。"'),
    ('"Stay on the current objective until it is done"', '"現在の対象が終わるまで継続する"'),
    ('"Objectives are re-ranked every tick. Without this, a skirmish that spawns and ranks\\n"', '"対象候補は毎tick再評価されます。この設定がOFFだと、途中でより高順位の対象が発生した際に\\n"'),
    ('"higher pulls the character off the fight it is already in."', '"現在戦闘中のスカーミッシュから離脱する可能性があります。"'),
    ('"Aces High, Beast of Man, And the Flames Went Higher, The Broken Blade, Head of the Snake,\\n"', '"ボズヤ/ザトゥノルの一騎打ちを対象にします。\\n"'),
    ('"Taking the Lyon\'s Share. Only one player is chosen and entry costs notoriety."', '"参加者は1名のみ選出され、参加条件・悪名度の影響があります。"'),
    ('ImGui.TextColored(Grey, "Castrum Lacus Litore and The Dalriada. Long, scheduled, usually organised runs.");', 'ImGui.TextColored(Grey, "カストルム・ラクスリトレおよび旗艦ダル・リアータを対象にします。通常CEより優先されます。");'),
    ('"Minimum registration window (s)"', '"参加申請する最低残り時間（秒）"'),
    ('"The game refuses registration under 10 seconds, so leave enough margin to actually get there."', '"残り10秒未満では申請できないため、UI処理分の余裕を確保します。"'),
    ('DrawRole("Tank",', 'DrawRole("タンク",'),
    ('DrawRole("Healer",', 'DrawRole("ヒーラー",'),
    ('ImGui.SetTooltip("Uses Mount Roulette past 30y, and dismounts on arrival so you can fight.");', 'ImGui.SetTooltip("30yを超える長距離ではマウントルーレットを使用し、到着時に戦闘可能な状態へ降ります。");'),
    ('"Arrival range (y)"', '"到着判定距離 (y)"'),
    ('"Stall timeout (s)"', '"移動スタック判定（秒）"'),
    ('"Zadnor\'s stacked terrain wedges ground paths regularly. When no real movement happens for\\n"', '"ザトゥノルの高低差などで地上経路が詰まった場合、実移動がこの時間発生しなければ\\n"'),
    ('"this long, the path is torn down, the destination re-snapped to the navmesh, and a fresh\\n"', '"現在経路を破棄して目的地をnavmeshへ再スナップし、\\n"'),
    ('"path issued."', '"新しい経路を作成します。"'),
    ('"Models FFXIV aggro as a forward SIGHT cone plus a smaller all-round PROXIMITY ring, so\\n"', '"敵感知を前方の視覚コーンと、全方向の近接感知リングとして扱います。\\n"'),
    ('"passing behind an enemy is allowed at a distance that would pull it head-on. Skipped\\n"', '"正面では感知される距離でも、背後なら安全な場合は通過できます。\\n"'),
    ('"entirely while actually flying - ground enemies cannot reach you up there."', '"本機能は地上移動用です。"'),
    ('"Sight radius (y)"', '"視覚感知距離 (y)"'),
    ('"Sight cone (deg)"', '"視覚感知角度 (度)"'),
    ('"Proximity radius (y)"', '"近接感知距離 (y)"'),
    ('ImGui.SetTooltip("Aggro range that ignores facing - it fires from directly behind too.");', 'ImGui.SetTooltip("向きに関係なく感知される距離です。真後ろでも適用されます。");'),
    ('"Detour clearance (y)"', '"迂回時の余裕距離 (y)"'),
    ('"How far to the side a detour steps past an enemy.\\n"', '"敵を迂回する際に横へどれだけ余裕を取るか指定します。\\n"'),
    ('"HIGHER IS SAFER HERE. Raising the sight radius makes detours HARDER to\\n"', '"大きいほど安全側です。視覚感知距離を増やすと迂回経路の成立条件が厳しくなり、\\n"'),
    ('"accept (there is more to clear); raising this makes them easier."', '"この値を増やすとより外側を通る経路を選びやすくなります。"'),
    ('"Ignore within of objective (y)"', '"目的地付近では迂回しない距離 (y)"'),
    ('"Enemies this close to the destination are the objective\'s own mobs.\\n"', '"目的地付近の敵はスカーミッシュ等の対象敵である可能性が高いため、\\n"'),
    ('"Routing around those would mean never arriving."', '"ここで迂回すると目的地へ到着できなくなるため無視します。"'),
    ('ImGui.TextColored(Grey, "Hostile enemies nearby (use this to set the level threshold):");', 'ImGui.TextColored(Grey, "周辺の敵（危険度判定の診断）:");'),
    ('$"  scanned {census.Combatants} combatant(s): {census.Accepted} tracked, "', '$"  検出 {census.Combatants}体: 追跡 {census.Accepted}, "'),
    ('$"{census.NotHostile} not flagged hostile, {census.BelowLevel} below the level "', '$"非敵対扱い {census.NotHostile}, 低危険度 {census.BelowLevel}, "'),
    ('$"threshold, {census.AlreadyOnUs} already on us, {census.OtherFloor} on another "', '$"既に自分を対象 {census.AlreadyOnUs}, 別階層 {census.OtherFloor}, "'),
    ('$"floor, {census.Suppressed} suppressed, {census.OutOfRange} out of range."', '$"一時除外 {census.Suppressed}, 範囲外 {census.OutOfRange}."'),
    ('"  Every nearby combatant was dropped for not carrying the hostile flag.\\n"', '"  周辺combatantがすべて非敵対フラグとして除外されています。\\n"'),
    ('"  That is the one reading that would silently disable avoidance entirely -\\n"', '"  通常のフィールド敵でもこの表示になる場合、敵判定が機能していません。\\n"'),
    ('"  if these are ordinary field mobs, report it."', '"  診断情報をコピーして確認してください。"'),
    ('ImGui.TextColored(Grey, "  none tracked");', 'ImGui.TextColored(Grey, "  追跡対象なし");'),
    ('"Stages inside the zone you are working, so the next thing to spawn is close. Zadnor\'s\\n"', '"対象エリア内の待機地点へ移動し、次のspawnへの初動距離を短くします。ザトゥノルは\\n"'),
    ('"plateaus are far enough apart that starting from the wrong one costs most of the\\n"', '"各台地が大きく離れているため、別エリアで待つと\\n"'),
    ('"registration window."', '"移動時間が大きくなります。"'),
    ('$"Staging points for {BozjaZones.Name(editable)} (map coordinates):"', '$"{BozjaZones.Name(editable)} の待機地点（マップ座標）:"'),
    ('$"Here##idle{key}"', '$"現在地##idle{key}"'),
    ('ImGui.SetTooltip("Set this staging point to where you are standing right now.");', 'ImGui.SetTooltip("この待機地点を現在立っている位置に設定します。");'),
    ('$"Clear##idle{key}"', '$"削除##idle{key}"'),
    ('"Both field zones are split into three regions, and the relic materials are\\n"', '"両フィールドは3エリアに分かれ、Relic素材はエリアごとに入手場所が異なります。\\n"'),
    ('"region-specific. In Zadnor, skirmishes and Critical Engagements inside the SAME\\n"', '"ザトゥノルでは同じ台地でもスカーミッシュとCEで\\n"'),
    ('"plateau drop different items - so farming the wrong third, or the wrong activity\\n"', '"入手素材が異なります。対象エリアまたは活動種別を間違えると\\n"'),
    ('"in the right third, yields nothing you need."', '"目的素材を取得できません。"'),
    ('DrawDropTable("Bozjan Southern Front",', 'DrawDropTable("南方ボズヤ戦線",'),
    ('DrawDropTable("Zadnor",', 'DrawDropTable("ザトゥノル高原",'),
    ('ImGui.TextColored(Grey, "Learned engagement regions");', 'ImGui.TextColored(Grey, "学習済みのイベントエリア");'),
    ('"There is no shipped table saying which region each Critical Engagement sits in, so\\n"', '"CEごとの所属エリアを示す固定テーブルがないため、\\n"'),
    ('"it is recorded the first time you stand at one. Until then an estimate from the map\\n"', '"初回到着時に実位置から記録します。それまではマップ上の推定位置を使用し、\\n"'),
    ('"region labels is used, which the learned value permanently replaces."', '"学習後は記録値を優先します。"'),
    ('$"Learned so far: {_regions.LearnedCount}"', '$"学習済み: {_regions.LearnedCount}"'),
    ('ImGui.Button("Forget learned regions")', 'ImGui.Button("学習済みエリアを削除")'),
    ('ImGui.SetTooltip("Use after a patch that moves engagements around.");', 'ImGui.SetTooltip("パッチ等でイベント位置が変わった場合に使用します。");'),
    ('"Skip objectives whose region is not yet known"', '"所属エリアが未判定の対象を除外する"'),
    ('"Off by default: visiting an unknown objective is how its region gets learned,\\n"', '"初期値はOFFです。未判定の対象へ実際に到着することで所属エリアを学習します。\\n"'),
    ('"and a fresh install would otherwise have nothing to do while farming a material."', '"ONにすると新規環境では対象が見つからなくなる可能性があります。"'),
    ('"Nothing has been learned yet, so with a farm target set this will skip everything."', '"まだエリア学習データがないため、Farm対象設定中はすべて除外される可能性があります。"'),
    ('"Log every UI callback to /xllog (debug)"', '"全UI callbackを /xllog へ記録する（デバッグ）"'),
    ('"For settling how the Resistance Recruitment window works.\\n"', '"ボズヤ関連UIの実callbackを調査するための診断機能です。\\n"'),
    ('"Nothing anywhere documents how a Register or Commence press is sent, so with\\n"', '"参加希望/戦闘突入やLost Finds Cacheなど、公開仕様がないUI操作を調べる場合に使用します。\\n"'),
    ('"this on, press those buttons BY HAND on a live engagement and /xllog will show\\n"', '"ONの状態でゲームUIを手動操作すると、/xllog に\\n"'),
    ('"the addon\'s real name and the exact arguments the game used.\\n"', '"addon名とゲームが使用したcallback引数を記録します。\\n"'),
    ('"Very noisy - it logs every addon in the client, not just this plugin\'s."', '"非常に大量のログが出ます。BBR以外のaddonも対象です。"'),
    ('ImGui.TextColored(Yellow, "  Logging every UI callback. Turn this off when you are done.");', 'ImGui.TextColored(Yellow, "  全UI callbackを記録中です。調査終了後はOFFにしてください。");'),
    ('ImGui.TableSetupColumn("Region"', 'ImGui.TableSetupColumn("エリア"'),
    ('ImGui.TableSetupColumn("Activity"', 'ImGui.TableSetupColumn("活動"'),
    ('ImGui.TableSetupColumn("Material"', 'ImGui.TableSetupColumn("素材"'),
    ('DropActivity.Skirmish => "Skirmish"', 'DropActivity.Skirmish => "スカーミッシュ"'),
    ('DropActivity.CriticalEngagement => "Critical Engagement"', 'DropActivity.CriticalEngagement => "クリティカルエンゲージメント"'),
    ('_ => "Any"', '_ => "どちらでも可"'),
    ('$"item {drop.ItemId}"', '$"アイテムID {drop.ItemId}"'),
    ('"Clicking the duty-action hotbar fires the action"', '"Duty Actionバーのクリックでアクションを使用する"'),
    ('"On by default. Your own two slots always answer; a peer\'s slot answers only from the\\n"', '"初期値はONです。自分の2枠は常に操作でき、他クライアントの枠は\\n"'),
    ('"host box, because only the host may instruct the group. Turn this off to put the\\n"', '"ホストからのみ操作できます。OFFにすると\\n"'),
    ('"window back to read-only."', '"Duty Actionウィンドウは表示専用になります。"'),
    ('"Duty-action window has no background"', '"Duty Actionウィンドウの背景を透明にする"'),
    ('"On by default, so the bar reads as an overlay on the game rather than a panel in front\\n"', '"初期値はONです。ゲーム画面上のオーバーレイとして表示します。\\n"'),
    ('"of it. The title bar stays either way - with the background gone it is the only thing\\n"', '"タイトルバーは残るため、背景を透明にしても\\n"'),
    ('"left to drag the window by."', '"そこをドラッグして移動できます。"'),
    ('"Off by default. Lost Actions are a farmed resource - burning them on trash is worse than\\n"', '"通常の自動使用設定です。ロストアクションは有限資源なので、\\n"'),
    ('"not using them. One entry per cooldown window, in the order listed below.\\n"', '"下記の優先順と使用間隔に従って1つずつ使用します。\\n"'),
    ('"Anything whose buff is already running is skipped and the window goes to the next entry,\\n"', '"既に同じバフが有効なものはスキップし、次候補へ進みます。\\n"'),
    ('"so an Essence is not re-drunk over itself every few seconds."', '"Essenceを無駄に上書きしません。"'),
    ('"...including pressing them, which SPENDS charges"', '"…Duty Actionも実際に発動してチャージを消費する"'),
    ('"Minimum gap (ms)"', '"最低使用間隔 (ms)"'),
    ('"Tick what to auto-use. \\"item\\" marks the entries the game consumes straight out of the\\n"', '"自動使用を許可する項目を選択します。「item」はHolsterから直接消費される種類です。\\n"'),
    ('"holster - those are used whether or not the press switch above is on."', '"Duty Action発動設定とは独立して消費されます。"'),
    ('$"{entry.Name}  (weight {entry.Weight}{kind})##la{entry.RowId}"', '$"{entry.Name}  (重量 {entry.Weight}{kind})##la{entry.RowId}"'),
    ('var kind = entry.IsItem ? ", item" : string.Empty;', 'var kind = entry.IsItem ? ", item" : string.Empty;'),
    ('ImGui.TextColored(Yellow, "(not pressed)");', 'ImGui.TextColored(Yellow, "（発動しません）");'),
    ('"A separate, stoppable task that keeps the party\'s Lost Action buffs up and heals whoever\\n"', '"パーティメンバーへのロストアクションバフ維持と、HPが低いメンバーへの回復を行う独立タスクです。\\n"'),
    ('"is worst off. Start and stop it from the main window. It only ever aims at your own\\n"', '"開始/停止はメイン画面から行います。対象は自分のパーティのみで、\\n"'),
    ('"party - never an alliance member or a passer-by - and it stops itself when it runs out."', '"アライアンスメンバーや周囲のプレイヤーには使用しません。在庫切れ時は停止します。"'),
    ('"Top up below (% of duration)"', '"残り効果時間が以下なら更新 (%)"'),
    ('"Heal below (% HP)"', '"このHP未満を回復 (%)"'),
    ('"Gap between casts (ms)"', '"使用間隔 (ms)"'),
    ('"Duty slot to load into"', '"ロード先Duty Action枠"'),
    ('"Tick what to maintain, in priority order. Only actions that can be aimed at a party\\n"', '"維持するアクションを優先順に選択します。パーティメンバーを対象にできるものだけを表示します。\\n"'),
    ('"member are listed - raises are excluded, and so are the two whose status cannot be\\n"', '"蘇生系と、状態判定できないアクションは除外します。\\n"'),
    ('"identified in the game data, since \\"do not re-apply what is already up\\" is the point."', '"既に有効なバフを重複使用しないことを優先します。"'),
    ('? "heal"', '? "回復"'),
    (': entry.HasDuration ? $"{Describe(entry.DurationSeconds)} buff" : "buff";', ': entry.HasDuration ? $"{Describe(entry.DurationSeconds)} バフ" : "バフ";'),
    ('"(no duration in the data - never topped up)"', '"（効果時間データなし - 自動更新しません）"'),
])

replace_many("Windows/RelicWindow.cs", [
    (': base("Resistance Relic###BozjaBuddyRebornRelic")', ': base("レジスタンス・ウェポン###BozjaBuddyRebornRelic")'),
    ('"otherwise only the stage you are on plus what is still outstanding"', '"OFFの場合は現在段階と未完了素材だけを表示します"'),
    ('bozja ? "Bozjan Southern Front unlocked" : "Bozjan Southern Front LOCKED (Hail to the Queen)"', 'bozja ? "南方ボズヤ戦線: 解放済み" : "南方ボズヤ戦線: 未解放（荒鷲の巣作戦）"'),
    ('zadnor ? "Zadnor unlocked" : "Zadnor LOCKED (A New Playing Field)"', 'zadnor ? "ザトゥノル高原: 解放済み" : "ザトゥノル高原: 未解放"'),
    ('ImGui.TextColored(Green, "Every tracked stage is complete.");', 'ImGui.TextColored(Green, "追跡対象の全段階が完了しています。");'),
    ('ImGui.TextColored(Blue, "Still outstanding across all stages");', 'ImGui.TextColored(Blue, "全段階の未完了素材");'),
    ('ImGui.TextColored(Grey, "The Bozja grind feeds several stages at once, so this is the real shopping list.");', 'ImGui.TextColored(Grey, "複数段階で必要になる素材をまとめて確認できます。");'),
    ('ImGui.TextColored(Green, "Nothing outstanding.");', 'ImGui.TextColored(Green, "不足素材はありません。");'),
    ('$"Stop##farm{m.ItemId}"', '$"停止##farm{m.ItemId}"'),
    ('$"Farm##farm{m.ItemId}"', '$"Farm##farm{m.ItemId}"'),
    ('$"Restrict the runner to {d.Describe()}.\\n"', '$"周回対象を {d.Describe()} に限定します。\\n"'),
    ('"Objectives elsewhere in the zone will be skipped."', '"対象外のイベントはスキップします。"'),
    ('ImGui.SetTooltip("Not farmed in the field zones - this plugin cannot route to it.");', 'ImGui.SetTooltip("フィールド内で取得する素材ではないため、このプラグインでは自動周回できません。");'),
    ('$"Farming: {active2.Describe()}"', '$"Farm中: {active2.Describe()}"'),
    ('"Clear##farmclear"', '"解除##farmclear"'),
    ('? (stage.OneTime ? "done" : "tier unlocked")', '? (stage.OneTime ? "完了" : "段階解放済み")'),
    (': p.QuestAccepted ? $"in progress (step {p.QuestSequence})" : "not started";', ': p.QuestAccepted ? $"進行中（step {p.QuestSequence}）" : "未開始";'),
    ('header += "  [one-time]";', 'header += "  [一度のみ]";'),
    ('p.MaterialsReady ? "Materials ready - go turn it in." : "Materials still short."', 'p.MaterialsReady ? "必要素材が揃っています。次の工程へ進めます。" : "必要素材が不足しています。"'),
])
